// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAynk8eBGFjwQ0APONfz2CH4yUMVx_lM7Q',
    appId: '1:806586564832:web:bf2abb9966603c2fb65085',
    messagingSenderId: '806586564832',
    projectId: 'vehiclemaintenancetrackerapp',
    authDomain: 'vehiclemaintenancetrackerapp.firebaseapp.com',
    storageBucket: 'vehiclemaintenancetrackerapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_h0r0bTfaUDt2HsQmsFByIUnOg1OCOEc',
    appId: '1:806586564832:android:7f52f86b70fc0a0cb65085',
    messagingSenderId: '806586564832',
    projectId: 'vehiclemaintenancetrackerapp',
    storageBucket: 'vehiclemaintenancetrackerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPdj10P0b3l1Qvnl5KkZxqsrS-48B64yA',
    appId: '1:806586564832:ios:5fbe75432f07fe59b65085',
    messagingSenderId: '806586564832',
    projectId: 'vehiclemaintenancetrackerapp',
    storageBucket: 'vehiclemaintenancetrackerapp.appspot.com',
    iosBundleId: 'com.example.vehicleMaintenanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPdj10P0b3l1Qvnl5KkZxqsrS-48B64yA',
    appId: '1:806586564832:ios:5fbe75432f07fe59b65085',
    messagingSenderId: '806586564832',
    projectId: 'vehiclemaintenancetrackerapp',
    storageBucket: 'vehiclemaintenancetrackerapp.appspot.com',
    iosBundleId: 'com.example.vehicleMaintenanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAynk8eBGFjwQ0APONfz2CH4yUMVx_lM7Q',
    appId: '1:806586564832:web:3e8f296795f09226b65085',
    messagingSenderId: '806586564832',
    projectId: 'vehiclemaintenancetrackerapp',
    authDomain: 'vehiclemaintenancetrackerapp.firebaseapp.com',
    storageBucket: 'vehiclemaintenancetrackerapp.appspot.com',
  );
}
